using System.Security.Cryptography;
using WaffleMeter.App.Core;
using WaffleMeter.Services;
using WaffleMeter.Stats;
using Xunit;

namespace WaffleMeter.App.Core.Tests;

/// <summary>
/// The meter reading an artifact the SERVER actually produced.
/// <para>Both halves are covered by their own tests and neither proves the pair works: the document is
/// written by TypeScript and read by C#, and every failure mode in between is silent. A digest computed over
/// the wrong bytes, a key renamed on one side, a gzip the other runtime cannot inflate — none of it raises
/// anything. The supporter simply has an ordinary nickname and nobody can tell why.</para>
/// <para>The fixture is a real artifact, byte for byte, generated by
/// <c>src/server/namefx/artifact.ts</c> in the stats web repo. To regenerate it, run that packer over the
/// same three rows (see the git history of this file's commit message).</para>
/// </summary>
public sealed class NameFxArtifactInteropTests : IDisposable
{
    /// <summary>Straight out of the server's own output, not recomputed here — the point is to check the two
    /// sides agree, and a value derived locally would agree with itself.</summary>
    private const string ExpectedSha256 = "56315e9303f1a7b8a4799af1876164d8896a27c8066b6bdae45fa85916650d53";
    private const string ExpectedArtifactId = "56315e9303f1a7b8";

    private static readonly string FixturePath =
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "namefx-artifact-v1.json.gz");

    private readonly string _dir = Path.Combine(Path.GetTempPath(), "waffle_namefx_interop_" + Guid.NewGuid().ToString("N"));

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch { /* best effort */ }
    }

    private static bool KnownEffect(string id) => NameFxIds.Effects.Contains(id);

    private static bool KnownGauge(string id) => NameFxIds.Gauges.Contains(id);

    [Fact]
    public void The_servers_digest_is_over_the_bytes_we_receive()
    {
        // 서버가 압축된 바이트를 해시하고, 미터도 압축된 바이트를 해시한다. 한쪽이 평문으로 옮겨 가면
        // 무결성 검사가 영원히 실패하고, 그 실패는 '연출이 안 붙는다'로만 보인다.
        byte[] gzip = File.ReadAllBytes(FixturePath);

        Assert.Equal(ExpectedSha256, Convert.ToHexStringLower(SHA256.HashData(gzip)));
        Assert.Equal(ExpectedArtifactId, ExpectedSha256[..16]);
    }

    [Fact]
    public void The_meter_reads_what_the_server_wrote()
    {
        byte[] gzip = File.ReadAllBytes(FixturePath);
        var props = new PropertyHandler(_dir);
        var api = new FixtureApi(gzip, ExpectedSha256, ExpectedArtifactId);

        using var service = new NameFxService(api, props, KnownEffect, KnownGauge, startWorker: false);
        service.TryRefresh();

        Assert.Null(service.Status().LastError);
        Assert.Equal(2, service.Roster.Count);

        // sha256("sha256:aion2-character:v1|1|와플") — the server computed this from (1, "와플") with its own
        // normaliser, and the meter looks it up with StatsIdentity. Same input, same hash, or no grant.
        NameFxEntry? supporter = service.Roster.Find(StatsIdentity.CharacterIdentityHash(1, "와플"));
        Assert.NotNull(supporter);
        Assert.Equal("syrup", supporter!.EffectId);
        Assert.Equal("supporter", supporter.Kind);
        Assert.Equal(0, supporter.ExpiresAtMs);
        Assert.Null(supporter.GaugeId);

        NameFxEntry? ranker = service.Roster.Find(StatsIdentity.CharacterIdentityHash(2, "Ranker"));
        Assert.NotNull(ranker);
        Assert.Equal("goldleaf", ranker!.EffectId);
        Assert.Equal("prism", ranker.GaugeId);
        Assert.Equal(DateTimeOffset.Parse("2026-08-22T00:00:00Z").ToUnixTimeMilliseconds(), ranker.ExpiresAtMs);
    }

    [Fact]
    public void The_character_who_did_not_consent_is_not_in_the_document_at_all()
    {
        // 서버가 실을지 말지 정하고, 미터는 받은 것을 그릴 뿐이다. 이 검사는 미터 쪽 게이트가 아니라
        // **문서에 애초에 없다**는 사실을 확인한다 — 배포된 명단은 회수할 방법이 없으므로, 동의 게이트가
        // 클라이언트에 있으면 이미 늦는다.
        byte[] gzip = File.ReadAllBytes(FixturePath);
        var props = new PropertyHandler(_dir);

        using var service = new NameFxService(
            new FixtureApi(gzip, ExpectedSha256, ExpectedArtifactId), props, KnownEffect, KnownGauge, startWorker: false);
        service.TryRefresh();

        Assert.Null(service.Roster.Find(StatsIdentity.CharacterIdentityHash(3, "미동의")));
    }

    [Fact]
    public void An_expired_lease_stops_rendering_even_though_the_document_still_carries_it()
    {
        // 랭커는 7일 리스다. 문서는 재발행 전까지 그 행을 그대로 담고 있으므로, 만료를 미터도 봐야 한다.
        byte[] gzip = File.ReadAllBytes(FixturePath);
        var props = new PropertyHandler(_dir);
        long afterExpiry = DateTimeOffset.Parse("2026-09-01T00:00:00Z").ToUnixTimeMilliseconds();

        using var service = new NameFxService(
            new FixtureApi(gzip, ExpectedSha256, ExpectedArtifactId), props, KnownEffect, KnownGauge,
            clock: () => afterExpiry, startWorker: false);
        service.TryRefresh();

        Assert.Null(service.Roster.Find(StatsIdentity.CharacterIdentityHash(2, "Ranker")));
        Assert.NotNull(service.Roster.Find(StatsIdentity.CharacterIdentityHash(1, "와플")));
    }

    /// <summary>The id lists the server publishes (<c>src/shared/supporters.ts</c>). Held here as literals so a
    /// rename on either side fails a test rather than dropping grants in silence.</summary>
    private static class NameFxIds
    {
        public static readonly HashSet<string> Effects = new(StringComparer.Ordinal)
        {
            "syrup", "butter", "berry", "crisp",
            "goldleaf", "platinum", "diamond", "flame", "glacier",
        };

        public static readonly HashSet<string> Gauges = new(StringComparer.Ordinal) { "prism", "ember", "frost" };
    }

    private sealed class FixtureApi(byte[] gzip, string sha, string artifactId) : INameFxApi
    {
        public NameFxManifestResponse GetNameFxManifest() =>
            new(true, artifactId, 1, $"/api/v1/supporters/artifact/{artifactId}.json", gzip.Length, sha);

        public StatsBinaryResponse GetNameFxArtifactGzip(string path) => new(200, gzip);
    }
}
