using System.Security.Cryptography;
using WaffleMeter.App.Core;
using WaffleMeter.Services;
using WaffleMeter.Stats;
using Xunit;

namespace WaffleMeter.App.Core.Tests;

/// <summary>
/// The meter reading an artifact the SERVER actually produced.
/// <para>Both halves are covered by their own tests and neither proves the pair works: the document is
/// written by TypeScript and read by C#, and every failure mode in between is silent. A digest computed over
/// the wrong bytes, a key renamed on one side, a gzip the other runtime cannot inflate — none of it raises
/// anything. The supporter simply has an ordinary nickname and nobody can tell why.</para>
/// <para>The fixture is a real artifact, byte for byte, generated by
/// <c>src/server/namefx/artifact.ts</c> in the stats web repo. To regenerate it, run that packer over the
/// same three rows (see the git history of this file's commit message).</para>
/// </summary>
public sealed class NameFxArtifactInteropTests : IDisposable
{
    /// <summary>Straight out of the server's own output, not recomputed here — the point is to check the two
    /// sides agree, and a value derived locally would agree with itself.</summary>
    private const string ExpectedSha256 = "f19ae5287d7e1833668b3967af37a65e4eeaffe9caaa447f4545056f17ad2193";
    private const string ExpectedArtifactId = "f19ae5287d7e1833";

    private static readonly string FixturePath =
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "namefx-artifact-v1.json.gz");

    private readonly string _dir = Path.Combine(Path.GetTempPath(), "waffle_namefx_interop_" + Guid.NewGuid().ToString("N"));

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch { /* best effort */ }
    }

    private static bool KnownEffect(string id) => NameFxIds.Effects.Contains(id);

    private static bool KnownGauge(string id) => NameFxIds.Gauges.Contains(id);

    [Fact]
    public void The_servers_digest_is_over_the_bytes_we_receive()
    {
        // 서버가 wire 로 나가는 바이트를 해시하고, 미터도 받은 그대로를 해시한다. 한쪽이 봉투 안쪽
        // (gzip 이나 평문)으로 옮겨 가면 무결성 검사가 영원히 실패하고, 그 실패는 '연출이 안 붙는다'로만
        // 보인다.
        byte[] wire = File.ReadAllBytes(FixturePath);

        Assert.Equal(ExpectedSha256, Convert.ToHexStringLower(SHA256.HashData(wire)));
        Assert.Equal(ExpectedArtifactId, ExpectedSha256[..16]);
    }

    [Fact]
    public void The_payload_is_sealed_and_the_meter_can_open_it()
    {
        // 봉투가 씌워져 있고 우리 키로 열린다는 것 — 즉 서버와 미터의 키가 같다는 것 — 을 확인한다.
        // 어긋나면 모든 설치본이 같은 순간에 복호에 실패하고, 화면에는 아무 표시도 없다.
        byte[] wire = File.ReadAllBytes(FixturePath);

        Assert.True(NameFxEnvelope.IsSealed(wire));
        byte[] inner = NameFxEnvelope.Open(wire);
        Assert.Equal(0x1f, inner[0]); // gzip magic
        Assert.Equal(0x8b, inner[1]);
    }

    [Fact]
    public void A_tampered_payload_does_not_open()
    {
        byte[] wire = File.ReadAllBytes(FixturePath);
        wire[^1] ^= 0x01;

        Assert.ThrowsAny<Exception>(() => NameFxEnvelope.Open(wire));
    }

    [Fact]
    public void The_meter_reads_what_the_server_wrote()
    {
        byte[] gzip = File.ReadAllBytes(FixturePath);
        var props = new PropertyHandler(_dir);
        var api = new FixtureApi(gzip, ExpectedSha256, ExpectedArtifactId);

        using var service = new NameFxService(api, props, KnownEffect, KnownGauge, startWorker: false);
        service.TryRefresh();

        Assert.Null(service.Status().LastError);
        Assert.Equal(2, service.Roster.Count);

        // sha256("sha256:aion2-character:v1|1|와플") — the server computed this from (1, "와플") with its own
        // normaliser, and the meter looks it up with StatsIdentity. Same input, same hash, or no grant.
        NameFxEntry? supporter = service.Roster.Find(StatsIdentity.CharacterIdentityHash(1, "와플"));
        Assert.NotNull(supporter);
        Assert.Equal("syrup", supporter!.EffectId);
        Assert.Equal("supporter", supporter.Kind);
        Assert.Equal(0, supporter.ExpiresAtMs);
        Assert.Null(supporter.GaugeId);

        NameFxEntry? ranker = service.Roster.Find(StatsIdentity.CharacterIdentityHash(2, "Ranker"));
        Assert.NotNull(ranker);
        Assert.Equal("goldleaf", ranker!.EffectId);
        Assert.Equal("prism", ranker.GaugeId);
        Assert.Equal(DateTimeOffset.Parse("2026-08-22T00:00:00Z").ToUnixTimeMilliseconds(), ranker.ExpiresAtMs);
    }

    [Fact]
    public void The_character_who_did_not_consent_is_not_in_the_document_at_all()
    {
        // 서버가 실을지 말지 정하고, 미터는 받은 것을 그릴 뿐이다. 이 검사는 미터 쪽 게이트가 아니라
        // **문서에 애초에 없다**는 사실을 확인한다 — 배포된 명단은 회수할 방법이 없으므로, 동의 게이트가
        // 클라이언트에 있으면 이미 늦는다.
        byte[] gzip = File.ReadAllBytes(FixturePath);
        var props = new PropertyHandler(_dir);

        using var service = new NameFxService(
            new FixtureApi(gzip, ExpectedSha256, ExpectedArtifactId), props, KnownEffect, KnownGauge, startWorker: false);
        service.TryRefresh();

        Assert.Null(service.Roster.Find(StatsIdentity.CharacterIdentityHash(3, "미동의")));
    }

    [Fact]
    public void An_expired_lease_stops_rendering_even_though_the_document_still_carries_it()
    {
        // 랭커는 7일 리스다. 문서는 재발행 전까지 그 행을 그대로 담고 있으므로, 만료를 미터도 봐야 한다.
        byte[] gzip = File.ReadAllBytes(FixturePath);
        var props = new PropertyHandler(_dir);
        long afterExpiry = DateTimeOffset.Parse("2026-09-01T00:00:00Z").ToUnixTimeMilliseconds();

        using var service = new NameFxService(
            new FixtureApi(gzip, ExpectedSha256, ExpectedArtifactId), props, KnownEffect, KnownGauge,
            clock: () => afterExpiry, startWorker: false);
        service.TryRefresh();

        Assert.Null(service.Roster.Find(StatsIdentity.CharacterIdentityHash(2, "Ranker")));
        Assert.NotNull(service.Roster.Find(StatsIdentity.CharacterIdentityHash(1, "와플")));
    }

    /// <summary>The id lists the server publishes (<c>src/shared/supporters.ts</c>). Held here as literals so a
    /// rename on either side fails a test rather than dropping grants in silence.</summary>
    private static class NameFxIds
    {
        public static readonly HashSet<string> Effects = new(StringComparer.Ordinal)
        {
            "syrup", "butter", "berry", "crisp",
            "goldleaf", "platinum", "diamond", "flame", "glacier",
        };

        public static readonly HashSet<string> Gauges = new(StringComparer.Ordinal) { "prism", "ember", "frost" };
    }

    private sealed class FixtureApi(byte[] gzip, string sha, string artifactId) : INameFxApi
    {
        public NameFxManifestResponse GetNameFxManifest() =>
            new(true, artifactId, 1, $"/api/v1/supporters/artifact/{artifactId}.json", gzip.Length, sha);

        public StatsBinaryResponse GetNameFxArtifactGzip(string path) => new(200, gzip);

        public NameFxChoiceResponse PostNameFxChoice(NameFxChoiceRequest request, string clientVersion, string? installId = null) =>
            new(true, "both", request.EffectId, request.GaugeId);
    }
}
